### ISSUE TITLE
course cannot be restored in beginner mode

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_experience#10]
If a user does not use the expert mode, he cannot restore courses as the Continue Button is not available.
![wiederherstellen](https://user-images.githubusercontent.com/22933650/102590276-9b8e2b80-4110-11eb-870f-6731f73cabca.PNG)

**Comment by rschrenk** [comment]
As discussed this is not a bug of local_experience, but an issue with the course backup file.
