### ISSUE TITLE
course restore preselect current course

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_experience#11]
When restoring a course in expert mode, the current course is not preselected. This leads to insecurity on the users side as a lot of courses of the user are listed and they might have similar names.

![grafik](https://user-images.githubusercontent.com/22933650/102590504-f889e180-4110-11eb-9867-7523a6750f18.png)

**Comment by rschrenk** [comment]
As discussed this is not a bug of local_experience, but an issue with the course backup file.
