### ISSUE TITLE
Examples for custom rules

### ISSUE THREAD

**Issue by bozicm** [center-for-learning-management/moodle-local_experience#13]
Hello!

Currently the plugin doesn't offer much documentation on how to configure the "Conditions" and "Rules" and "Relation conditions <=> rules". It would be very nice to have Default value example as in the case of `local_experience | attachlevelselectto` for each site. "Rules" site seems to have some useful bits, but "Conditions" and Conditions-Rules sites help seem too cryptic.

**Comment by rschrenk** [comment]
Hello,

indeed the documentation is lacking here. The idea behind it was that you can specify rules that can be applied to pages based on certain conditions. But the feature did not really work well enough, so I am not sure if I won't drop it anyway.

Kind regards
